# Generated by Django 2.0.3 on 2018-03-31 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180331_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preço',
            new_name='preco',
        ),
    ]
